#yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json

package: api
generate:
  echo-server: true
  models: true
  embedded-spec: true
output: ../pkg/api/gen.go
output-options:
